name: Node CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:  # generally only for the "combine-prs" workflow
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Static Tests
            command: bin/static_tests
          - name: Static Lint
            command: bin/static_lint
          - name: Static Pipeline
            command: bin/static_pipeline
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24.0.0
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Run ${{ matrix.name }}
        run: ${{ matrix.command }}
